### ISSUE TITLE
Parse construction GeoJson file

### ISSUE THREAD

**Issue by SimonJinaphant** [SimonJinaphant/Discovr#58]

**Comment by sansnickel** [comment]
If we're just trying to get values i can help with this

**Comment by SimonJinaphant** [comment]
@sansnickel 

Yeah I just need to extract the "name" and "coordinate" fields.
You see the structure by going to the[ raw geojson file](https://raw.githubusercontent.com/SimonJinaphant/Discovr/master/app/src/main/assets/construction.geojson), copy-paste into the json text field of [ the website here](http://geojson.io/#map=16/49.2650/-123.2518), and CTRL+S for it to auto format what you pasted.

What I'm interested in is the "name" and "coordinate" fields

**Comment by SimonJinaphant** [comment]
Closed with #76
