### ISSUE TITLE
Add GeoJson file for bus loop stops

### ISSUE THREAD

**Issue by SimonJinaphant** [SimonJinaphant/Discovr#60]

**Comment by sansnickel** [comment]
Do you want the bus stops as single coordinate points?

**Comment by SimonJinaphant** [comment]
@sansnickel 

Yes, here's an[ example](https://github.com/SimonJinaphant/Discovr/blob/simon/bus_loop_geojson/app/src/main/assets/busloop.geojson) of what I have for the geojson

In general each marker has 3 fields (The name is still up for debates):
- BusStop - The station number you use to query the Transit API with
- Name - The general name for the bus stop, I only added this because it could simply search
- Bus - JSONArray of the bus(es) that stop at this station
