### ISSUE TITLE
Events: Web crawler

### ISSUE THREAD

**Issue by ValRat** [SimonJinaphant/Discovr#94]
Create a web crawler which traverses the UBC events page and retrieves events information to input into the database. 
http://www.events.ubc.ca/

**Comment by dh221** [comment]
Web Crawler Report
1) Scrape one single event from UBC event web-page ----Completed
2) Multi-scraping a list of events ----On Process
3) Sending collected event data to Remote Database

**Comment by dh221** [comment]
Web Crawler Report
-Scrape a list of events that's happening within a week
-Sending collected event data to Remote Database (testing)
